version: "3.7"
services:
  storybook:
    build:
      context: .
    command: "npm run storybook:dev"
    ports:
      - "5000:5000"
    volumes:
      - "./src:/app/src"
      - "./.storybook:/app/.storybook"
