version: "3.7"
services:
  storybook:
    build:
      context: .
    command: "npm run storybook:dev"
    ports:
      - "5000:5000"
    volumes:
      - "./tsconfig.json:/app/tsconfig.json"
      - "./src:/app/src"
      - "./stories:/app/stories"
      - "./.storybook:/app/.storybook"
